# Page defaults
base_url = "https://jakublesko.com/"
title = "Jakub Leško"
description = "Blog about programming and technology in general"

# Enable RSS feed generation
generate_feed = true

# Enable syntax highlighting
highlight_code = true
highlight_theme = "nord"
